biopen_element_add:
    path:     /add
    defaults: { _controller: BiopenElementBundle:Element:add }

biopen_element_edit:
    path:     /edit/{id}
    defaults: { _controller: BiopenElementBundle:Element:edit }
    requirements:
        id: \d+

biopen_element_delete:
    path:     /delete/{id}
    defaults: { _controller: BiopenElementBundle:Element:delete }
    requirements:
        id: \d+

biopen_element_generate:
    path:     /generate/{nombre}
    defaults: { _controller: BiopenElementBundle:RandomCreation:generate, nombre:'1' }
    options:
        expose: true
