biopen_element_add:
    path:     /add
    defaults: { _controller: BiopenElementBundle:ElementForm:add }

biopen_element_edit:
    path:     /edit/{id}
    defaults: { _controller: BiopenElementBundle:ElementForm:edit }
    requirements:
        id: \d+

biopen_element_delete:
    path:     /delete/{id}
    defaults: { _controller: BiopenElementBundle:ElementForm:delete }
    requirements:
        id: \d+

biopen_element_generate:
    path:     /generate/{nombre}
    defaults: { _controller: BiopenElementBundle:RandomCreation:generate, nombre:'1' }
    options:
        expose: true

biopen_api_element_by_id:
    path:     /api/element
    defaults: { _controller: BiopenElementBundle:API:getElementById }
    requirements:
        _method: POST
    options:
        expose: true

biopen_api_elements_around_location:
    path:     /api/elementsAround
    defaults: { _controller: BiopenElementBundle:API:getElementsAroundLocation }
    requirements:
        _method: POST
    options:
        expose: true


