biopen_api_ui:
    path: /
    defaults: { _controller: BiopenCoreBundle:API:apiUi }

biopen_api_manifest:
    path:     /manifest.{_format}
    defaults: { _controller: BiopenCoreBundle:API:getManifest, _format: json }
    requirements:
        methods: GET
        _format: json

biopen_api_project_info:
    path:     /project-info.{_format}
    defaults: { _controller: BiopenCoreBundle:API:getProjectInfo, _format: json }
    requirements:
        methods: GET
        _format: json
