biopen_homepage:
    path:     /
    defaults: { _controller: BiopenCoreBundle:Core:index }

biopen_constellation:
    path:     /constellation/{slug}
    defaults: { _controller: BiopenCoreBundle:Core:constellation, slug:'' }
    options:
        expose: true

biopen_constellation_ajax:
    path:     /constellationAjax
    defaults: { _controller: BiopenCoreBundle:Core:constellationAjax }
    requirements:
        _method: POST
    options:
        expose: true

biopen_listing:
    path:     /list/{slug}
    defaults: { _controller: BiopenCoreBundle:Core:listing, slug:'France' }
    options:
        expose: true