services:
  my_user_provider:
        class: Application\Sonata\UserBundle\Security\FOSUBUserProvider
        arguments: [@fos_user.user_manager,{facebook: facebookUid, gplus: gplusUid, communs: communsUid}]

  biopen.authentication_handler:
      class: Application\Sonata\UserBundle\Security\AuthenticationHandler
      public: false
      arguments: [ '@router', '@session', '@security.context']
        
  biopen.config_service:
    class: Biopen\CoreBundle\Services\ConfigurationService
    arguments: [ "@doctrine.odm.mongoDB.document_manager", "@security.context" ]

  biopen.mail_service:
    class: Biopen\CoreBundle\Services\MailService
    arguments: [ "@doctrine.odm.mongoDB.document_manager", "@mailer", "@router", "@twig", "%base_url%", "%base_path%", "%use_as_saas" ]

  biopen.newsletter_service:
    class: Biopen\CoreBundle\Services\NewsletterService
    arguments: [ "@doctrine.odm.mongoDB.document_manager", "@biopen.mail_service" ]

  biopen.upload_directory_namer:
    class: Biopen\CoreBundle\Services\UploadDirectoryNamer
    arguments: []