services:
  biopen.config_service:
    class: Biopen\CoreBundle\Services\ConfigurationService
    arguments: [ "@doctrine.odm.mongoDB.document_manager", "@security.context" ]

  biopen.mail_service:
    class: Biopen\CoreBundle\Services\MailService
    arguments: [ "@doctrine.odm.mongoDB.document_manager", "@mailer", "@router", "@twig" ]

  biopen.newsletter_service:
    class: Biopen\CoreBundle\Services\NewsletterService
    arguments: [ "@doctrine.odm.mongoDB.document_manager", "@biopen.mail_service" ]