services:
    bopen_fournisseur.form.fournisseur:
        class: Biopen\FournisseurBundle\Form\FournisseurType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
#    biopen_fournisseur.example:
#        class: Biopen\FournisseurBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
