sonata_user:
    security_acl: true
    impersonating:
        route: sonata_admin_dashboard
    manager_type: mongodb # can be orm or mongodb
    class:                  # Entity Classes
        user:               Biopen\CoreBundle\Document\User
        group:              Application\Sonata\UserBundle\Document\Group

    admin:                  # Admin Classes
        user:
            class:          Biopen\CoreBundle\Admin\UserAdmin
            controller:     BiopenCoreBundle:UserAdmin
            translation:    SonataUserBundle

        group:
            class:          Sonata\UserBundle\Admin\Document\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle        

fos_user:
    db_driver:      mongodb # can be orm or mongodb
    firewall_name:  main
    user_class:     Biopen\CoreBundle\Document\User
    registration:
        form:
            type: biopen_user_registration
        confirmation:
            enabled: true
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address:        nepasrepondre@presdecheznous.fr
        sender_name:    Près de chez nous

    group:
        group_class:   Application\Sonata\UserBundle\Document\Group
        group_manager: sonata.user.mongodb.group_manager                    # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

    service:
        user_manager: sonata.user.mongodb.user_manager                      # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)

hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]
    target_path_parameter: _destination
    use_referer: true
    fosub:
        username_iterations: 30
        properties:
            google: gplusUid
            facebook : facebook_id
    resource_owners:
        gplus:
            type:                google
            client_id:           718756240856-nqjk8stfevmbjoklqctvec8avtci3oac.apps.googleusercontent.com
            client_secret:       c2j_wuyI7lo3kECCkB9nbmcr
            scope:               "email profile"
            options:
                display: popup #dialog is optimized for popup window
                csrf: true
        facebook:
            type:                facebook
            client_id:           723073984538238
            client_secret:       44cbf0bb6892e8d8bfd890357e9b6951
            scope:               "public_profile,email"
            options:
                display: popup #dialog is optimized for popup window
                auth_type: rerequest # Re-asking for Declined Permissions
        yahoo:
            type:                yahoo
            client_id:           dj0yJmk9VlJSaEY2MTZIODVCJmQ9WVdrOWJGRlhUMjVJTlRnbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD03Nw--
            client_secret:       babaa2b0eb6dc3d580f08f8ad298115409abae0c
