biopen_core:
    resource: "@BiopenCoreBundle/Resources/config/routing.yml"
    prefix:   /

biopen_fournisseur:
    resource: "@BiopenFournisseurBundle/Resources/config/routing.yml"
    prefix:   /fournisseur

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

