biopen_core:
    resource: "@BiopenCoreBundle/Resources/config/routing.yml"
    prefix:   /

biopen_geo_directory:
    resource: "@BiopenGeoDirectoryBundle/Resources/config/routing.yml"
    prefix:   /




