biopen_back_office:
    resource: "@BiopenBackOfficeBundle/Controller/"
    type:     annotation
    prefix:   /backoffice

biopen_core:
    resource: "@BiopenCoreBundle/Resources/config/routing.yml"
    prefix:   /

biopen_element:
    resource: "@BiopenElementBundle/Resources/config/routing.yml"
    prefix:   /acteurs

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

