services:
    my_user_provider:
        class: Application\Sonata\UserBundle\Security\FOSUBUserProvider
        arguments: [@fos_user.user_manager,{facebook: facebookUid, gplus: gplusUid, yahoo: twitterUid}]

    biopen.authentication_handler:
        class: Application\Sonata\UserBundle\Security\AuthenticationHandler
        public: false
        arguments: [ '@router', '@session', '@security.context']

    jms_serializer.naming_strategy_camelCase:
        class: 'JMS\Serializer\Naming\IdenticalPropertyNamingStrategy'

    jms_serializer.naming_strategy:
        class: 'JMS\Serializer\Naming\SerializedNameAnnotationStrategy'
        arguments : ['@jms_serializer.naming_strategy_camelCase']