biopen_special_actions_update_json:
    path:     /updateJson
    defaults: { _controller: Biopen\GeoDirectoryBundle\Controller\Admin\SpecialActionsController::updateJsonAction }
    requirements:
        _method: GET

biopen_special_actions_fixs_mail_address:
    path:     /fixsEmailAddresses
    defaults: { _controller: Biopen\GeoDirectoryBundle\Controller\Admin\SpecialActionsController::fixsEmailAddressesAction }
    requirements:
        _method: GET

biopen_special_actions_fixs_cicuits_court:
    path:     /fixsCircuitsCourts
    defaults: { _controller: Biopen\GeoDirectoryBundle\Controller\Admin\SpecialActionsController::fixsCircuitsCourtAction }
    requirements:
        _method: GET
