biopen_api_element_by_id:
    path:     /element
    defaults: { _controller: BiopenGeoDirectoryBundle:API:getElementById }
    requirements:
        _method: POST
    options:
        expose: true

biopen_api_elements_around_location:
    path:     /elementsAround
    defaults: { _controller: BiopenGeoDirectoryBundle:API:getElementsAroundLocation }
    requirements:
        _method: POST
    options:
        expose: true
