biopen_element:
    resource: "@BiopenGeoDirectoryBundle/Resources/config/routing-element-form.yml"
    prefix:   /acteurs

biopen_directory:
    resource: "@BiopenGeoDirectoryBundle/Resources/config/routing-directory.yml"

biopen_api:
    resource: "@BiopenGeoDirectoryBundle/Resources/config/routing-api.yml"
    prefix:   /api

biopen_vote:
    resource: "@BiopenGeoDirectoryBundle/Resources/config/routing-element-interaction.yml"
    prefix: /interact

biopen_special_actions:
    resource: "@BiopenGeoDirectoryBundle/Resources/config/routing-special-actions.yml"
    prefix: /specialActions

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"