biopen_api_taxonomy:
    path:     /taxonomy
    defaults: { _controller: BiopenGeoDirectoryBundle:API:getTaxonomy }
    requirements:
        _method: GET
    options:
        expose: true

biopen_api_elements_from_text:
    path:     /elements/search
    defaults: { _controller: BiopenGeoDirectoryBundle:API:getElementsFromText }
    requirements:
        _method: GET
    options:
        expose: true

biopen_api_element_get:
    path:     /elements/{id}.{_format}
    defaults: { _controller: BiopenGeoDirectoryBundle:API:getElements, id: null, _format: json }
    requirements:
        _method: GET
        _format: json|jsonld
    options:
        expose: true

biopen_api_elements_index:
    path:     /elements.{_format}
    defaults: { _controller: BiopenGeoDirectoryBundle:API:getElements, id: null, _format: json }
    requirements:
        _method: GET
        _format: json|jsonld
    options:
        expose: true


