biopen_element_add:
    path:     /add
    defaults: { _controller: BiopenGeoDirectoryBundle:ElementForm:add }

biopen_element_edit:
    path:     /edit/{id}
    defaults: { _controller: BiopenGeoDirectoryBundle:ElementForm:edit }
    options:
        expose: true

biopen_element_check_duplicate:
    path:     /check-doublons
    defaults: { _controller: BiopenGeoDirectoryBundle:ElementForm:checkDuplicates }

biopen_element_delete:
    path:     /delete/{id}
    defaults: { _controller: BiopenGeoDirectoryBundle:ElementForm:delete }

biopen_element_generate:
    path:     /generate/{nombre}/{generateVotes}
    defaults: { _controller: BiopenGeoDirectoryBundle:Import:generateRandom, nombre:'1', generateVotes:'0' }

biopen_element_import_colibris_lmc:
    path:     /import-colibris-lmc/{fileName}/{geocode}
    defaults: { _controller: BiopenGeoDirectoryBundle:Import:importColibrisLmc, geocode:'0'}

biopen_element_update_colibris_lmc:
    path:     /update-colibris-lmc/{fileName}
    defaults: { _controller: BiopenGeoDirectoryBundle:Import:updateColibrisLmc }



