biopen_directory_normal:
    path:     /{mode}/{addressAndViewport}
    defaults: { _controller: BiopenGeoDirectoryBundle:Directory:normal,  addressAndViewport:'' }
    options:
        expose: true
    requirements:
        mode: carte|liste

biopen_directory_showElement:
    path:     /acteur/{name}/{id}/{addressAndViewport}
    defaults: { _controller: BiopenGeoDirectoryBundle:Directory:showElement, addressAndViewport:''}
    options:
        expose: true
    requirements:
        id: \d+

biopen_directory_showDirections:
    path:     /itineraire/{name}/{id}/{addressAndViewport}
    defaults: { _controller: BiopenGeoDirectoryBundle:Directory:showDirections, addressAndViewport:''}
    options:
        expose: true
    requirements:
        id: \d+

biopen_directory_constellation:
    path:     /{mode}/constellation/{address}/{range}
    defaults: { _controller: BiopenGeoDirectoryBundle:Directory:constellation, address: '', range:'50' }
    options:
        expose: true
    requirements:
        range: \d+
        mode: carte|liste

biopen_directory_directions:
    path:     /dir/{address}/{name}/{id}
    defaults: { _controller: BiopenGeoDirectoryBundle:Directory:directions }
    options:
        expose: true


