biopen_api_taxonomy:
    path:     /taxonomy
    defaults: { _controller: BiopenGeoDirectoryBundle:API:getTaxonomy }
    requirements:
        _method: GET
    options:
        expose: true

biopen_api_elements_from_text:
    path:     /elements/search
    defaults: { _controller: BiopenGeoDirectoryBundle:API:getElementsFromText }
    requirements:
        _method: GET
    options:
        expose: true

biopen_api_elements:
    path:     /elements/{id}
    defaults: { _controller: BiopenGeoDirectoryBundle:API:getElements, id: null }
    requirements:
        _method: GET
    options:
        expose: true


