biopen_special_actions_update_json:
    path:     /updateJson
    defaults: { _controller: Biopen\GeoDirectoryBundle\Controller\Admin\SpecialActionsController::updateJsonAction }
    requirements:
        _method: GET

biopen_special_actions_update_options_string:
    path:     /updateOptionsString
    defaults: { _controller: Biopen\GeoDirectoryBundle\Controller\Admin\SpecialActionsController::updateElementOptionsStringAction }
    requirements:
        _method: GET

biopen_special_actions_fixs_mail_address:
    path:     /fixsEmailAddresses
    defaults: { _controller: Biopen\GeoDirectoryBundle\Controller\Admin\SpecialActionsController::fixsEmailAddressesAction }
    requirements:
        _method: GET

biopen_special_actions_random_hash:
    path:     /generateRandomHash
    defaults: { _controller: Biopen\GeoDirectoryBundle\Controller\Admin\SpecialActionsController::generateRandomHashAction }
    requirements:
        _method: GET

biopen_special_actions_fixs_cicuits_court:
    path:     /fixsCircuitsCourts
    defaults: { _controller: Biopen\GeoDirectoryBundle\Controller\Admin\SpecialActionsController::fixsCircuitsCourtAction }
    requirements:
        _method: GET

biopen_special_actions_add_import_contribution:
    path:     /addImportContribution
    defaults: { _controller: Biopen\GeoDirectoryBundle\Controller\Admin\SpecialActionsController::addImportContributionAction }
    requirements:
        _method: GET

biopen_special_actions_fix_cities:
    path:     /fixsMissingCities
    defaults: { _controller: Biopen\GeoDirectoryBundle\Controller\Admin\SpecialActionsController::fixsMissingCitiesAction }
    requirements:
        _method: GET

biopen_special_actions_verify_duplicates:
    path:     /verifyDuplicates
    defaults: { _controller: Biopen\GeoDirectoryBundle\Controller\Admin\SpecialActionsController::verifyDuplicatesAction }
    requirements:
        _method: GET

biopen_special_actions_detect_duplicates:
    path:     /detectDuplicates
    defaults: { _controller: Biopen\GeoDirectoryBundle\Controller\Admin\SpecialActionsController::detectDuplicatesAction }
    requirements:
        _method: GET

biopen_special_actions_delete_element_reported:
    path:     /deleteElementReportedAsNoMoreExisting
    defaults: { _controller: Biopen\GeoDirectoryBundle\Controller\Admin\SpecialActionsController::deleteElementReportedAsNoMoreExistingAction }
    requirements:
        _method: GET

biopen_special_actions_update_gamification:
    path:     /updateGamification
    defaults: { _controller: Biopen\GeoDirectoryBundle\Controller\Admin\SpecialActionsController::updateGamificationAction }
    requirements:
        _method: GET
