biopen_element:
    resource: "@BiopenGeoDirectoryBundle/Resources/config/routing-element-form.yml"
    prefix:   /acteurs

biopen_directory:
    resource: "@BiopenGeoDirectoryBundle/Resources/config/routing-directory.yml"
    prefix:   /nav

biopen_api:
    resource: "@BiopenGeoDirectoryBundle/Resources/config/routing-api.yml"
    prefix:   /api

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"