services:
    biopen.form.element:
        class: Biopen\GeoDirectoryBundle\Form\ElementType
        arguments: [ "@doctrine.odm.mongoDB.document_manager" ]
        tags:
            - { name: form.type }
    biopen.element_service:
       class: Biopen\GeoDirectoryBundle\Services\ElementService
       arguments: [ "@doctrine.odm.mongoDB.document_manager" ]
