services:
    biopen.form.element:
        class: Biopen\GeoDirectoryBundle\Form\ElementType
        arguments: [ "@doctrine.odm.mongoDB.document_manager" ]
        tags:
            - { name: form.type }

    biopen.element_vote_service:
       class: Biopen\GeoDirectoryBundle\Services\ElementVoteService
       arguments: [ "@doctrine.odm.mongoDB.document_manager", "@security.context", "@biopen.config_service", "@biopen.element_pending_service" ]

    biopen.element_action_service:
       class: Biopen\GeoDirectoryBundle\Services\ElementActionService
       arguments: [ "@security.context", "@biopen.mail_service", "@biopen.element_pending_service" ]

    biopen.element_pending_service:
       class: Biopen\GeoDirectoryBundle\Services\ElementPendingService
       arguments: [ "@doctrine.odm.mongoDB.document_manager", "@security.context", "@biopen.mail_service" ]

    biopen.element_form_service:
       class: Biopen\GeoDirectoryBundle\Services\ElementFormService
       arguments: [ "@biopen.element_action_service" ]

    biopen.element_duplicates_service:
       class: Biopen\GeoDirectoryBundle\Services\ElementDuplicatesService
       arguments: [ "@doctrine.odm.mongoDB.document_manager" ]

    biopen.random_creation_service:
       class: Biopen\GeoDirectoryBundle\Services\RandomCreationService
       arguments: [ "@doctrine.odm.mongoDB.document_manager" ]

    biopen.json_generator:
        class: Biopen\GeoDirectoryBundle\EventListener\JsonRepresentationGenerator
        arguments: [ '@jms_serializer' ]
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: postPersist }
            - { name: doctrine_mongodb.odm.event_listener, event: postUpdate }
            - { name: doctrine_mongodb.odm.event_listener, event: postRemove }

    biopen.csvtoarray:
        class: Biopen\GeoDirectoryBundle\Services\ConvertCsvToArrayService

    biopen.import_colibris_lmc:
       class: Biopen\GeoDirectoryBundle\Services\ImportColibrisLmcService
       arguments: [ "@doctrine.odm.mongoDB.document_manager", "@biopen.csvtoarray", '@bazinga_geocoder.geocoder' ]

    biopen.update_colibris_lmc:
       class: Biopen\GeoDirectoryBundle\Services\UpdateColibrisLmcService
       arguments: [ "@doctrine.odm.mongoDB.document_manager", "@biopen.csvtoarray"]


